// <auto-generated />
using System;
using MeisterProPR.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeisterProPR.Infrastructure.Migrations
{
    [DbContext(typeof(MeisterProPRDbContext))]
    [Migration("20260321212505_AddResolvePrComments")]
    partial class AddResolvePrComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeisterProPR.Domain.Entities.MentionPrScan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CrawlConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("crawl_configuration_id");

                    b.Property<DateTimeOffset>("LastCommentSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_comment_seen_at");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("pull_request_id");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CrawlConfigurationId", "RepositoryId", "PullRequestId")
                        .IsUnique()
                        .HasDatabaseName("uq_mention_pr_scans_pr");

                    b.ToTable("mention_pr_scans", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.MentionProjectScan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CrawlConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("crawl_configuration_id");

                    b.Property<DateTimeOffset>("LastScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scanned_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CrawlConfigurationId")
                        .IsUnique()
                        .HasDatabaseName("uq_mention_project_scans_config");

                    b.ToTable("mention_project_scans", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.MentionReplyJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<int>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("MentionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mention_text");

                    b.Property<string>("OrganizationUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_url");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_id");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("pull_request_id");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("ThreadId")
                        .HasColumnType("integer")
                        .HasColumnName("thread_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_mention_reply_jobs_client_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_mention_reply_jobs_status");

                    b.HasIndex("ClientId", "PullRequestId", "ThreadId", "CommentId")
                        .IsUnique()
                        .HasDatabaseName("uq_mention_reply_jobs_mention");

                    b.ToTable("mention_reply_jobs", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("IterationId")
                        .HasColumnType("integer")
                        .HasColumnName("iteration_id");

                    b.Property<string>("OrganizationUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_url");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_id");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("pull_request_id");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository_id");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_review_jobs_client_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_review_jobs_status");

                    b.HasIndex("OrganizationUrl", "ProjectId", "RepositoryId", "PullRequestId", "IterationId")
                        .HasDatabaseName("ix_review_jobs_pr_identity");

                    b.ToTable("review_jobs", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewPrScan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("LastProcessedCommitId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_processed_commit_id");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("pull_request_id");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "RepositoryId", "PullRequestId")
                        .IsUnique()
                        .HasDatabaseName("uq_review_pr_scans_pr");

                    b.ToTable("review_pr_scans", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewPrScanThread", b =>
                {
                    b.Property<Guid>("ReviewPrScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_pr_scan_id");

                    b.Property<int>("ThreadId")
                        .HasColumnType("integer")
                        .HasColumnName("thread_id");

                    b.Property<int>("LastSeenReplyCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_seen_reply_count");

                    b.HasKey("ReviewPrScanId", "ThreadId");

                    b.ToTable("review_pr_scan_threads", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Infrastructure.Data.Models.ClientRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdoClientId")
                        .HasColumnType("text")
                        .HasColumnName("ado_client_id");

                    b.Property<string>("AdoClientSecret")
                        .HasColumnType("text")
                        .HasColumnName("ado_client_secret");

                    b.Property<string>("AdoTenantId")
                        .HasColumnType("text")
                        .HasColumnName("ado_tenant_id");

                    b.Property<int>("CommentResolutionBehavior")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("comment_resolution_behavior");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_key");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Infrastructure.Data.Models.CrawlConfigurationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<int>("CrawlIntervalSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("crawl_interval_seconds");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("OrganizationUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_url");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_crawl_configurations_client_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_crawl_configurations_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("ClientId", "OrganizationUrl", "ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_crawl_configurations_unique_config");

                    b.ToTable("crawl_configurations", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.MentionPrScan", b =>
                {
                    b.HasOne("MeisterProPR.Infrastructure.Data.Models.CrawlConfigurationRecord", null)
                        .WithMany()
                        .HasForeignKey("CrawlConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.MentionProjectScan", b =>
                {
                    b.HasOne("MeisterProPR.Infrastructure.Data.Models.CrawlConfigurationRecord", null)
                        .WithMany()
                        .HasForeignKey("CrawlConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.MentionReplyJob", b =>
                {
                    b.HasOne("MeisterProPR.Infrastructure.Data.Models.ClientRecord", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewPrScan", b =>
                {
                    b.HasOne("MeisterProPR.Infrastructure.Data.Models.ClientRecord", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewPrScanThread", b =>
                {
                    b.HasOne("MeisterProPR.Domain.Entities.ReviewPrScan", "ReviewPrScan")
                        .WithMany("Threads")
                        .HasForeignKey("ReviewPrScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewPrScan");
                });

            modelBuilder.Entity("MeisterProPR.Infrastructure.Data.Models.CrawlConfigurationRecord", b =>
                {
                    b.HasOne("MeisterProPR.Infrastructure.Data.Models.ClientRecord", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewPrScan", b =>
                {
                    b.Navigation("Threads");
                });
#pragma warning restore 612, 618
        }
    }
}
